### ISSUE TITLE
"Direction" button doesn't work on my (any?) address

### ISSUE THREAD

**Issue by iandees** [dphiffer/alloftheplaces.xyz#1]
Steps to reproduce:
1. Go to https://alloftheplaces.xyz/
2. Search for "20 Link Rd, Lexington, VA"
3. Click the red "Directions" button in the popup
4. ???
5. No profit 😢 

Expected:
1. Profit!

If I do this with a city (e.g. "Milwaukee, WI") it appears to request browser geolocation, so I think something's missing.

**Comment by dphiffer** [comment]
Yay, first bug! Thanks @iandees, this should be fixed now.

💰
